## Data encoding is the process of converting data from one format to another so that it can be used effectively by computers or ML models.

In ML, encoding usually refers to transforming categorical or text data into numerical form, because most models only understand numbers.

### One-Hot Encoding
Converts each category(Column) into a binary vector.

Each category becomes a column with 0 or 1.

Color = ["Red", "Green", "Blue"]

One-Hot Encoded →

Red   → [1, 0, 0]

Green → [0, 1, 0]

Blue  → [0, 0, 1]

In [127]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [128]:
df = pd.DataFrame({
    'Color': ['Red', 'Green', 'Blue', 'Red', 'Green']})
df.head()

   Color
0    Red
1  Green
2   Blue
3    Red
4  Green

In [129]:
# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [130]:
encoded = encoder.fit_transform(df[['Color']]).toarray()

In [131]:
import pandas as pd 
encoder_df = pd.DataFrame(encoded,columns= encoder.get_feature_names_out())

In [132]:
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0

In [133]:
encoder.transform([['Blue']]).toarray()

e:\Machine_Learning\myenv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [134]:
pd.concat([df,encoder_df],axis = 1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1  Green         0.0          1.0        0.0
2   Blue         1.0          0.0        0.0
3    Red         0.0          0.0        1.0
4  Green         0.0          1.0        0.0

## Label Encoding
Label Encoding is a data preprocessing technique used in Machine Learning to convert categorical (text) data into numerical form, because ML algorithms work with numbers, not strings.

In [135]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [136]:
lbl_encoder.fit_transform(df[['Color']])

e:\Machine_Learning\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 2, 1])

In [137]:
lbl_encoder.transform([['Red']])

e:\Machine_Learning\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### Ordinal - Encoding
When a categorical feature has a meaningful order, ordinal encoding preserves that order.

High School → 0

Bachelor    → 1

Master      → 2

PhD         → 3

In [138]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({'data' : ['Low', 'Medium', 'High', 'High','Low']})
df

     data
0     Low
1  Medium
2    High
3    High
4     Low

In [139]:
encoder = OrdinalEncoder(categories = [['Low','Medium','High']])

In [140]:
encoder.fit_transform(df[['data']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.]])

### Target-Guided Ordinal Encoding
(also called Target Encoding with ordering) is an advanced categorical encoding technique where categories are ordered and encoded based on their relationship with the target variable.

In [141]:
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [144]:
mean_price = df.groupby('city')['price'].mean().to_dict() # Group by city ...mean on price

In [145]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [ ]:
df['city_encoded'] = df['city'].map(mean_price) # .map() replaces values in a column using a mapping
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0