In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('index_price.csv')
df.head(2)

   company earnings  interest rate  inflation  market demand  index_price
0             29.43          27.36      10.66          79.85       321.01
1             54.35          25.02       2.52          33.81       257.26

In [5]:
df.drop(columns = ["company earnings","interest rate"], axis = 1,inplace = True)

In [6]:
df.head(3)

   inflation  market demand  index_price
0      10.66          79.85       321.01
1       2.52          33.81       257.26
2       7.20          38.05       223.43