# Pandas Data Manipulation - Beginner to Intermediate Guide

## 🎯 What is Pandas?
Pandas is Python's primary library for working with data. If your data was a spreadsheet (like Excel), Pandas lets you manipulate it programmatically. It's the bridge between raw data and data analysis!

## 📊 Why Learn Pandas?
- **Handle Real Data**: Load and work with messy, real-world data
- **Quick Analysis**: Calculate statistics without complex code
- **Data Cleaning**: Fix missing values, remove duplicates, format data
- **Integration**: Perfect tool before visualizing or modeling your data
- **Industry Standard**: Used by most data professionals

## 🗂️ Core Data Structures

### Series (1D Data)
- Like a column in a spreadsheet
- One dimension with index labels
- Example: list of student grades

### DataFrame (2D Data)
- Like a full spreadsheet with rows and columns
- Multiple dimensions (rows and columns)
- Example: employee data with name, salary, department

## 📚 Beginner's Learning Path

### Section 1: Core Concepts & Getting Started
**Goal**: Understand basic data structures and how to create them

**Topics Covered**:
- Import Pandas and NumPy
- Create a Series from a list
- Create a Series with custom index labels
- Create a DataFrame from a dictionary
- Understand DataFrame structure

**Why This Matters**: You need to know how to create and understand data before you can analyze it

### Section 2: Exploring Your Data (The First Steps)
**Goal**: Learn how to look at and understand your data

**Key Methods**:
- `df.info()` - Get overview of data (types, missing values)
- `df.head()` - See first few rows
- `df.tail()` - See last few rows
- `df.shape` - How many rows and columns?
- `df.columns` - What are the column names?
- `df.describe()` - Statistical summary (mean, min, max, etc.)
- `df.dtypes` - What data types do we have?

**Why This Matters**: Before analyzing data, you MUST understand it first

### Section 3: Selecting Data (Finding What You Need)
**Goal**: Learn different ways to extract data from your DataFrame

**Techniques**:
- Select single column: `df['ColumnName']`
- Select multiple columns: `df[['Col1', 'Col2']]`
- Select rows by position: `df.iloc[0:5]` (first 5 rows)
- Select rows by label: `df.loc[0:2]` (rows labeled 0-2)
- Filter by condition: `df[df['Age'] > 30]` (all rows where Age > 30)

**Why This Matters**: You rarely want all data; you need to focus on specific parts

### Section 4: Data Manipulation (Making Changes)
**Goal**: Learn how to add, remove, and modify data

**Operations**:
- Add new column: `df['NewCol'] = values`
- Remove column: `df.drop('ColumnName', axis=1)`
- Rename columns: `df.rename(columns={'OldName': 'NewName'})`
- Sort data: `df.sort_values('ColumnName')`
- Apply functions: `df['Column'].apply(lambda x: x * 2)`

**Why This Matters**: Real data needs cleaning and organizing

### Section 5: Handling Missing Data (Dealing with Problems)
**Goal**: Find and fix incomplete data

**Issues & Solutions**:
- Identify missing: `df.isnull().sum()` - How much missing data?
- Fill missing: `df.fillna(0)` - Replace with specific value
- Drop missing: `df.dropna()` - Remove rows with missing values
- Forward fill: `df.fillna(method='ffill')` - Use previous value

**Why This Matters**: Most real-world data has gaps that you must handle

### Section 6: Data Aggregation (Summarizing Data)
**Goal**: Calculate summary statistics and group data

**Operations**:
- Mean: `df['Column'].mean()` - Average value
- Sum: `df['Column'].sum()` - Total
- Count: `df['Column'].count()` - How many non-missing?
- Group By: `df.groupby('Category')['Value'].mean()` - Average per category
- Pivot tables: Create summaries organized by multiple dimensions

**Why This Matters**: Turn raw data into actionable insights

### Section 7: Combining Data (Merging Multiple Sources)
**Goal**: Join data from different sources

**Techniques**:
- Concatenate: Combine rows from multiple DataFrames
- Merge: Join based on common columns (like SQL JOIN)
- Join: Combine based on index

**Why This Matters**: Real analysis often requires combining data from multiple sources

### Section 8: Loading & Saving Data (In & Out)
**Goal**: Work with data files

**File Formats**:
- CSV: `pd.read_csv('file.csv')` - Most common format
- Excel: `pd.read_excel('file.xlsx')` - Spreadsheet format
- JSON: `pd.read_json('file.json')` - Web data format
- Database: SQL queries directly to DataFrame

**Why This Matters**: Data lives in files; you need to load and save it

### Section 9:

## 🎯 Step-by-Step Example
```python
# 1. Load data
df = pd.read_csv('data.csv')

# 2. Explore data
print(df.head())          # First look
print(df.info())          # Summary
print(df.describe())      # Statistics

# 3. Clean data
df = df.dropna()          # Remove missing values
df = df.drop_duplicates() # Remove duplicates

# 4. Analyze data
average = df['Age'].mean() # Calculate average
by_group = df.groupby('Department')['Salary'].mean() # Group analysis

# 5. Visualize
df.plot(kind='bar')       # Quick visualization
```

## 💡 Common Questions Beginners Ask

**Q: What's the difference between Series and DataFrame?**
A: Series is 1 column; DataFrame is multiple columns (like full spreadsheet)

**Q: Why use Pandas instead of Excel?**
A: For large datasets, complex operations, and reproducible analysis

**Q: How do I handle missing data?**
A: Decide: Drop it, Fill it, or Leave it based on your analysis

**Q: What's groupby?**
A: Split data into groups, apply function, combine results. Like PIVOT in Excel.

## 🚀 Practice Strategy
1. Start with small DataFrames (10-20 rows)
2. Master selection and filtering first
3. Then add aggregation and grouping
4. Finally try data merging
5. Apply to real datasets

## 📌 Remember
- **Explore First**: Always use `head()`, `info()`, `describe()` first
- **Verify Changes**: Check data after each operation
- **Save Often**: Don't lose your work!
- **Read Error Messages**: Python tells you what went wrong
- **Use Documentation**: When stuck, look up pandas docs

## **Dataframes**

In [1]:
# Import required libraries for data analysis
import pandas as pd
import numpy as np

In [2]:
# Check Pandas version
pd.__version__

'2.3.1'

In [3]:
# Create a Series from a list (1D labeled data structure)
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(s)

pandas.core.series.Series

In [5]:
# Create a Series with custom index labels
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
# Create a DataFrame from a dictionary (2D labeled data structure)
df = pd.DataFrame({'A': [1, 4, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [7]:
# Get DataFrame information: shape, columns, dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [8]:
# Get shape of the DataFrame (rows, columns)
print(df.shape)

(3, 3)

In [9]:
# Get first few rows of the DataFrame
df.head()

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [10]:
# Get last few rows of the DataFrame
df.tail()

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [11]:
# Get column names
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [12]:
# Get index labels
df.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
# Get data types of each column
df.dtypes

A    int64
B    int64
C    int64
dtype: object

In [14]:
# Get statistical summary of numerical columns
df.describe()

              A    B    C
count  3.000000  3.0  3.0
mean   2.666667  5.0  8.0
std    1.527525  1.0  1.0
min    1.000000  4.0  7.0
25%    2.000000  4.5  7.5
50%    3.000000  5.0  8.0
75%    3.500000  5.5  8.5
max    4.000000  6.0  9.0

In [15]:
# Check for missing values
df.isnull().sum()

A    0
B    0
C    0
dtype: int64

In [16]:
# Get more detailed statistics
df.describe(include='all')

              A    B    C
count  3.000000  3.0  3.0
mean   2.666667  5.0  8.0
std    1.527525  1.0  1.0
min    1.000000  4.0  7.0
25%    2.000000  4.5  7.5
50%    3.000000  5.0  8.0
75%    3.500000  5.5  8.5
max    4.000000  6.0  9.0

## Loading in Dataframes from Files

In [17]:
# Select a single column
df['A']

0    1
1    4
2    3
Name: A, dtype: int64

In [18]:
# Select multiple columns
df[['A', 'C']]

   A  C
0  1  7
1  4  8
2  3  9

In [19]:
df.head()

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [20]:
# Select rows by position using iloc (integer location)
df.iloc[0:2]

   A  B  C
0  1  4  7
1  4  5  8

In [21]:
# Select rows by label using loc (label location) if has a index 
df.loc[0:1]
df.loc[1, 'A']

np.int64(4)

## Accessing Data with Pandas

In [22]:
df

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [23]:
# Boolean filtering - select rows where column A > 2
print(df[df['A'] > 2])

   A  B  C
1  4  5  8
2  3  6  9

In [24]:
# Add a new column to the DataFrame
df['D'] = [10, 20, 30]
df

   A  B  C   D
0  1  4  7  10
1  4  5  8  20
2  3  6  9  30

In [25]:
# Drop a column from the DataFrame
df_dropped = df.drop('D', axis=1)
df_dropped

   A  B  C
0  1  4  7
1  4  5  8
2  3  6  9

In [26]:
# Rename columns using a dictionary mapping
df_renamed = df.rename(columns={'A': 'Column_A', 'B': 'Column_B'})
df_renamed

   Column_A  Column_B  C   D
0         1         4  7  10
1         4         5  8  20
2         3         6  9  30

In [27]:
# Sort DataFrame by a column in ascending order
# Values asociated with A also changes too 
df.sort_values('A')

   A  B  C   D
0  1  4  7  10
2  3  6  9  30
1  4  5  8  20

In [28]:
# Sort DataFrame by multiple columns
df_multi_sort = df.sort_values(by=['A', 'B'], ascending=[True, False])
print(df_multi_sort)

   A  B  C   D
0  1  4  7  10
2  3  6  9  30
1  4  5  8  20

In [29]:
# Apply a function to each element in a column
df['A_squared'] = df['A'].apply(lambda x: x ** 2)
df['B_squared'] = df['B'].apply(lambda x: x ** 2)
df

   A  B  C   D  A_squared  B_squared
0  1  4  7  10          1         16
1  4  5  8  20         16         25
2  3  6  9  30          9         36

In [30]:
# Calculate mean, sum, and count of columns
df[['A', 'B', 'C']].mean()

A    2.666667
B    5.000000
C    8.000000
dtype: float64

#### iloc

In [31]:
# Load data from CSV file
df_csv = pd.read_csv('zomato.csv')
df_csv.head(3)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270

#### Other Stuff

In [32]:
# Check shape of loaded data
print(df_csv.shape)

(9551, 21)

In [33]:
# Get data types and info
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [34]:
# Check for missing values in the loaded data
print(df_csv.isnull().sum())

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [35]:
df_csv.fillna(0)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [36]:
df_csv.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [37]:
# Apply function
df_csv['Latitude_new'] = df_csv['Latitude'].apply(lambda x : x*2)
df_csv.head(1)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Latitude_new
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,29.130886

#### Data aggregating and grouping

In [38]:
df = pd.read_csv('coffee.csv')

In [39]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [40]:
grp_mean = df.groupby('Coffee Type')['Units Sold'].mean()
print(grp_mean)

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [41]:
grp_sum = df.groupby(['Day','Coffee Type'])['Units Sold'].sum()
print(grp_sum)

Day        Coffee Type
Friday     Espresso       45
           Latte          35
Monday     Espresso       25
           Latte          15
Saturday   Espresso       45
           Latte          35
Sunday     Espresso       45
           Latte          35
Thursday   Espresso       40
           Latte          30
Tuesday    Espresso       30
           Latte          20
Wednesday  Espresso       35
           Latte          25
Name: Units Sold, dtype: int64

In [42]:
# Multiple aggregate function 

grp_agg = df.groupby(['Day'])['Units Sold'].agg(['mean','sum','count'])
print(grp_agg)

           mean  sum  count
Day
Friday     40.0   80      2
Monday     20.0   40      2
Saturday   40.0   80      2
Sunday     40.0   80      2
Thursday   35.0   70      2
Tuesday    25.0   50      2
Wednesday  30.0   60      2

#### Merging and joining dataframes

In [43]:
df1 = pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value1':[4,5,6]})

In [44]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [45]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [46]:
# Returns only the rows that match in BOTH tables.
pd.merge(df1,df2, on ='Key', how = 'inner')

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [47]:
# Returns matching rows PLUS non-matching rows (with NULL values).
pd.merge(df1,df2, on ='Key', how = 'outer')

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [48]:
pd.merge(df1,df2, on ='Key', how = 'left')

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [49]:
pd.merge(df1,df2, on ='Key', how = 'right')

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6